### ISSUE TITLE
Library not work

### ISSUE THREAD

**Issue by akbarraihan** [RCHowell/flutter_plot#3]
![image](https://user-images.githubusercontent.com/56537178/77505219-23eae300-6e95-11ea-92b1-51b7be195e13.png)

**Comment by akbarraihan** [comment]
when i run the project, the messages is show like that

**Comment by RaulMarquezInclan** [comment]
Lookup the value of PI to six decimals (I think, maybe more) and replace that PI constant with your own PI variable.

**Comment by rchowell** [comment]
@RaulMarquezInclan that's what the pi constant in the standard library is for

@akbarraihan this was written some time ago, and the dart language has changed a bit. The PI constant was redefined to just "pi". See here -- [dart:math](https://api.flutter.dev/flutter/dart-math/pi-constant.html)

This is a great opportunity to make a pull request! Please do not do what Raul suggested.

**Comment by MarcoSoares11** [comment]
Is this issue going to be solved? I am in the need of using this library and would be happy if it was solved.

UPDATE:
I just noticed how easy it was to change the variable PI to pi, thank you anyways, great plot!

**Comment by RenatFakhrutdinov** [comment]
@RCHowell 
Hi!
I prepared pull request with a solution of this issue
https://github.com/RCHowell/flutter_plot/pull/4

**Comment by rchowell** [comment]
Latest revision has been uploaded

https://pub.dev/packages/flutter_plot/versions/0.0.3
